### ISSUE TITLE
Actinobacteria_otu_map.txt empty

### ISSUE THREAD

**Issue by anmwinter** [jfmeadow/q2oligo#1]
Hello,

 I am using q2oligo to look at the Actinobacteria from my QIIME files. I am using OS X 10.9, python 2.7, and QIIME 1.8 with the greengenes database. 

When I run:
python q2oligo.py rep_set_tax_assignments.txt seqs_otus.txt "Actinobacteria"

Everything prints to screen. The program says it finds 2009 OTUs.

...............................
    Searching the taxonomy file
...............................

...............................
    Finished searching the taxonomy file
    Found 2009 OTUs matching "Actinobacteria"
...............................

...............................
    Searching the OTU map
    This might take a minute
...............................

...............................
    Finished searching the OTU map
    Found 2009 OTUs and wrote them to Actinobacteria_otu_map.txt

When I check the Actinobacteria_otu_map.txt it is empty. But the Actinobacteria_taxonomy.txt file has what it is supposed. 

Any suggestions? 

Thanks!
ara

**Comment by jfmeadow** [comment]
I'm not sure. Can you send the top 3 lines from seqs_otus.txt? This command will do it: 
head -n 3 seqs_otus.txt
