### ISSUE TITLE
much less reads retained than expected

### ISSUE THREAD

**Issue by yoyohashao** [jfmeadow/q2oligo#2]
latest version. 
QIIME 1.8, OS X 10.2
Issue:
The taxonomy file showed there were over 100 OTUs of interested taxa. However, the otu_map only contained 15ish OTUs, which resulted in much less reads were captured from seqs.fna.

**Comment by jfmeadow** [comment]
Without knowing your situation, the most likely explanation is using one of the several otu_map files produced during open ref OTU picking. QIIME produces several of these, and choosing the wrong one will result in your incorrectly matched output. If you used the open ref OTU picking method, the otu map should be called `final_otu_map_mc2.txt`. If you used another otu map, that would explain the problem.

**Comment by yoyohashao** [comment]
Dear Jeff,

 I took your advice and got the reads I wanted. Thanks.

Best,Fang

Fang Liu
PhD Candidate
Rm. 3-410 School of Life Sciences and Biotechnology
Shanghai Jiaotong University
Shanghai,China 200240
https://www.researchgate.net/profile/Fang_Liu37

**Comment by jfmeadow** [comment]
Great.
